default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hirogaru_art_development
  username: hirogaru_art
  password: your_secure_password
  host: localhost
  port: 5432

test:
  <<: *default
  database: hirogaru_art_test
  username: hirogaru_art
  password: your_secure_password
  host: localhost
  port: 5432

production:
  <<: *default
  database: hirogaru_art_production
  username: hirogaru_art
  password: <%= ENV["HIROGARU_ART_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432